name: buddhi-pragati
channels:
  - pytorch
  - huggingface
  - conda-forge
  - defaults

dependencies:
  # Python version
  - python=3.10

  # Core ML/DL packages (better from conda)
  - pytorch>=2.6.0
  - numpy>=1.21.0
  - scipy>=1.9.0
  - pandas>=1.5.0
  - scikit-learn>=1.0.0
  
  # Development and analysis tools
  - pip
  - git
  - jupyter
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - plotly>=5.10.0
  
  # NLP tools (available via conda)
  - nltk>=3.7
  - spacy>=3.4.0
  
  # Pip-only packages
  - pip:
    # Core NLP and transformers
    - transformers>=4.21.0
    - datasets>=2.0.0
    - tokenizers>=0.13.0
    - huggingface-hub>=0.16.0
    - sentence-transformers>=2.0.0
    
    # Configuration and utilities
    - pyyaml>=6.0
    - tqdm>=4.64.0
    - regex>=2022.7.9
    - editdistance>=0.6.0
    
    # Indian language processing
    - pyiwn>=0.0.4
    
    # API model support
    - openai>=1.0.0
    - anthropic>=0.3.0
    - requests>=2.28.0
    - sarvamai>=0.1.0

    # Development and testing tools
    - pytest>=7.0.0
    - pytest-cov>=4.0.0
    - black>=22.0.0
    - mypy>=0.991
    - flake8>=5.0.0
    - ruff>=0.0.289
    - pre-commit>=2.20.0
    - psutil>=5.9.0
